### ISSUE TITLE
notokan

### ISSUE THREAD

**Issue by bphd** [1nikolas/play-integrity-checker-app#39]
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): [358] ugx.b\(\d+\): requestIntegrityToken() failed for gr.nikolasspyr.integritycheck.
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): [389] nvo.c\(\d+\): Unexpected android-id = 0
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): 	at android.app.ActivityThread.main(ActivityThread.java:8594)
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): 	at android.os.Handler.dispatchMessage(Handler.java:100)
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): 	at android.os.Handler.handleCallback(Handler.java:959)
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): 	at android.os.Looper.loop(Looper.java:317)
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): 	at android.os.Looper.loopOnce(Looper.java:232)
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): 	at java.lang.reflect.Method.invoke(Native Method)
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): Caused by: DisplayErrorMessage[Error retrieving information from server. DF-DFERH-01]
\d+-\d+ \d+:\d+:\d+.\d+ E/Finsky  \(\d+\): com.google.android.finsky.integrityservice.IntegrityException
\d+-\d+ \d+:\d+:\d+.\d+ E/HandwritingModeController\(\d+\): Cannot get requestId: Handwriting was not initialized.
\d+-\d+ \d+:\d+:\d+.\d+ E/Parcel  \(\d+\): Attempt to read from protected data in Parcel 0x\S+
\d+-\d+ \d+:\d+:\d+.\d+ E/Parcel  \(\d+\): Expecting header 0x\S+ but found 0x\S+ Mixing copies of libbinder?
\d+-\d+ \d+:\d+:\d+.\d+ E/TaskPersister\(\d+\): File error accessing recents directory (directory doesn't exist?).
\d+-\d+ \d+:\d+:\d+.\d+ E/tas_spk_prot\(\d+\): call enable_sa_path
\d+-\d+ \d+:\d+:\d+.\d+ E/Volley  \(\d+\): [389] kat.a: Unexpected response code 400 for https://play-fe.googleapis.com/fdfe/integrity

**Comment by bphd** [comment]
> Try again later it should be a temporary problem

Nope, the case since forever

**Comment by bphd** [comment]
Was probably about my cerification status rather than the application

Idk if I still experiencing the error, haven't checked logs, but by deactivating `persist.sys.pixelprops.gapps` `persist.sys.pixelprops.gms` properties and resintalling vending/gsf/gms and spoofing build and provider (and btw using PIF module, or Osm0sis one when that one bother me) I achieve device integrity. I have difficulties achieving strong integrity but it's probably because my CROM throw `UnsupportedOperationException()` when DroidGuard ask for certificate chain, have to figure out how to patch from MagiSK, or LSP, or by replacing files

**Comment by 1nikolas** [comment]
Not the app's issue
